INSERT INTO symptoms VALUES (238, "Anxiety");
INSERT INTO symptoms VALUES (104, "Back pain");
INSERT INTO symptoms VALUES (75, "Burning eyes");
INSERT INTO symptoms VALUES (46, "Burning in the throat");
INSERT INTO symptoms VALUES (170, "Cheek swelling");
INSERT INTO symptoms VALUES (17, "Chest pain");
INSERT INTO symptoms VALUES (31, "Chest tightness");
INSERT INTO symptoms VALUES (175, "Chills");
INSERT INTO symptoms VALUES (139, "Cold sweats");
INSERT INTO symptoms VALUES (15, "Cough");
INSERT INTO symptoms VALUES (207, "Dizziness");
INSERT INTO symptoms VALUES (244, "Drooping eyelid");
INSERT INTO symptoms VALUES (273, "Dry eyes");
INSERT INTO symptoms VALUES (87, "Earache");
INSERT INTO symptoms VALUES (92, "Early satiety");
INSERT INTO symptoms VALUES (287, "Eye pain");
INSERT INTO symptoms VALUES (33, "Eye redness");
INSERT INTO symptoms VALUES (153, "Fast, deepened breathing");
INSERT INTO symptoms VALUES (76, "Feeling of foreign body in the eye");
INSERT INTO symptoms VALUES (11, "Fever");
INSERT INTO symptoms VALUES (57, "Going black before the eyes");
INSERT INTO symptoms VALUES (9, "Headache");
INSERT INTO symptoms VALUES (45, "Heartburn");
INSERT INTO symptoms VALUES (122, "Hiccups");
INSERT INTO symptoms VALUES (149, "Hot flushes");
INSERT INTO symptoms VALUES (40, "Increased thirst");
INSERT INTO symptoms VALUES (73, "Itching eyes");
INSERT INTO symptoms VALUES (96, "Itching in the nose");
INSERT INTO symptoms VALUES (35, "Lip swelling");
INSERT INTO symptoms VALUES (235, "Memory gap");
INSERT INTO symptoms VALUES (112, "Menstruation disorder");
INSERT INTO symptoms VALUES (123, "Missed period");
INSERT INTO symptoms VALUES (44, "Nausea");
INSERT INTO symptoms VALUES (136, "Neck pain");
INSERT INTO symptoms VALUES (114, "Nervousness");
INSERT INTO symptoms VALUES (133, "Night cough");
INSERT INTO symptoms VALUES (12, "Pain in the limbs");
INSERT INTO symptoms VALUES (203, "Pain on swallowing");
INSERT INTO symptoms VALUES (37, "Palpitations");
INSERT INTO symptoms VALUES (140, "Paralysis");
INSERT INTO symptoms VALUES (54, "Reduced appetite");
INSERT INTO symptoms VALUES (14, "Runny nose");
INSERT INTO symptoms VALUES (29, "Shortness of breath");
INSERT INTO symptoms VALUES (124, "Skin rash");
INSERT INTO symptoms VALUES (52, "Sleeplessness");
INSERT INTO symptoms VALUES (95, "Sneezing");
INSERT INTO symptoms VALUES (13, "Sore throat");
INSERT INTO symptoms VALUES (64, "Sputum");
INSERT INTO symptoms VALUES (179, "Stomach burning");
INSERT INTO symptoms VALUES (28, "Stuffy nose");
INSERT INTO symptoms VALUES (138, "Sweating");
INSERT INTO symptoms VALUES (248, "Swollen glands in the armpits");
INSERT INTO symptoms VALUES (169, "Swollen glands on the neck");
INSERT INTO symptoms VALUES (211, "Tears");
INSERT INTO symptoms VALUES (16, "Tiredness");
INSERT INTO symptoms VALUES (115, "Tremor at rest");
INSERT INTO symptoms VALUES (144, "Unconsciousness, short");
INSERT INTO symptoms VALUES (101, "Vomiting");
INSERT INTO symptoms VALUES (181, "Vomiting blood");
INSERT INTO symptoms VALUES (56, "Weakness");
INSERT INTO symptoms VALUES (23, "Weight gain");
INSERT INTO symptoms VALUES (30, "Wheezing");